const EAST_BEARING = 'EAST';
const NORTH_BEARING = 'NORTH';
const SOUTH_BEARING = 'SOUTH';
const WEST_BEARING = 'WEST';

export {
    EAST_BEARING,
    NORTH_BEARING,
    SOUTH_BEARING,
    WEST_BEARING
}